# Generated by Django 6.0.5 on 2026-05-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_wagtailsearch_indexentry_text_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=50, unique=True, verbose_name='Resource')),
                ('last_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Last updated at')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='Last success at')),
            ],
            options={
                'verbose_name': 'Core sync state',
                'verbose_name_plural': 'Core sync states',
            },
        ),
        migrations.AlterField(
            model_name='flexibledate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='license',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='licensestatement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
