# Generated by Django 6.0.5 on 2026-05-31 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markup_doc', '0002_alter_articledocx_estatus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articledocxmarkup',
            name='dateiso',
        ),
        migrations.RemoveField(
            model_name='articledocxmarkup',
            name='issid_part',
        ),
        migrations.RemoveField(
            model_name='articledocxmarkup',
            name='month',
        ),
        migrations.RemoveField(
            model_name='articledocxmarkup',
            name='supplno',
        ),
        migrations.RemoveField(
            model_name='articledocxmarkup',
            name='supplvol',
        ),
        migrations.RemoveField(
            model_name='articledocxmarkup',
            name='vol',
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Issue number')),
                ('volume', models.CharField(blank=True, max_length=20, null=True, verbose_name='Issue volume')),
                ('season', models.CharField(blank=True, help_text='Ex: Jan-Abr.', max_length=20, null=True, verbose_name='Issue season')),
                ('year', models.CharField(blank=True, max_length=4, null=True, verbose_name='Issue year')),
                ('month', models.CharField(blank=True, max_length=20, null=True, verbose_name='Issue month')),
                ('supplement', models.CharField(blank=True, max_length=20, null=True, verbose_name='Supplement')),
                ('creator', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='markup_doc.journalmodel', verbose_name='Journal')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='articledocxmarkup',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='markup_doc.issue', verbose_name='Issue'),
        ),
    ]
