# Generated by Django 6.0.5 on 2026-05-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markup_doc', '0002_alter_articledocx_estatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledocxmarkup',
            name='marked_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads_docx_marked/', verbose_name='Marked Document'),
        ),
    ]
